# Generated by Django 5.1.1 on 2024-10-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productoo',
        ),
    ]
